///////////////////////////////////////////////////////////////////////////////
// CppBetterMoveInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CppBetterMoveServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
