///////////////////////////////////////////////////////////////////////////////
// GivePosition.cpp
#include "TcPch.h"
#pragma hdrstop

#include "GivePosition.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CGivePosition
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CGivePosition
BEGIN_INTERFACE_MAP(CGivePosition)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CGivePosition)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CGivePosition)
IMPLEMENT_ITCADI(CGivePosition)
IMPLEMENT_ITCWATCHSOURCE(CGivePosition)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CGivePosition 
BEGIN_SETOBJPARA_MAP(CGivePosition)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_GivePositionParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CGivePosition 
BEGIN_GETOBJPARA_MAP(CGivePosition)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_GivePositionParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CGivePosition
BEGIN_OBJPARAWATCH_MAP(CGivePosition)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CGivePosition
BEGIN_OBJDATAAREA_MAP(CGivePosition)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_GivePositionInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_GivePositionOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CGivePosition::CGivePosition()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
	, Pi(3.14159f)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
	//for (int i = 0; i < 100; i++)
	//{
	//	MyCppPosition[i] = 0;
	//}
	//double tp1[5] = { 0.5, 0.7, 0.2, 1.0, 1.9 };
	//double tp2[5] = { 2.5, 2.0, 2.9, 3.5, 2.8 };
	//for (int i = 0; i < 5; i++)
	//{
	//	testPosition1[i] = tp1[i];
	//	testPosition2[i] = tp2[i];
	//}
	//double ta1[5] = { 3, 0, 2.1, 3.3, 5.8 };
	//double ta2[5] = { 8.2, 10.1, 12.9, 13.5, 12.8 };
	//for (int i = 0; i < 5; i++)
	//{
	//	testAngle1[i] = ta1[i];
	//	testAngle2[i] = ta2[i];
	//}
	//PositionCount = 0;			//位置数组数据移动到第几个坐标
	//PositionArraySize = 0;		//位置数组有多少个坐标
	//shoulderMaxPos = 10;		//肘关节最多移动位置
	//counter = 0;
}

///////////////////////////////////////////////////////////////////////////////
CGivePosition::~CGivePosition() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CGivePosition)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CGivePosition::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CGivePosition::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CGivePosition::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CGivePosition::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// TODO: Add deinitialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

double testPos = 20;
double testAng = 80;

HRESULT CGivePosition::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// TODO: Replace the sample with your cyclic code
	
	//timer = m_Inputs.PlcTimer;
	//if (timer > 2)
	//{
	//	switch (counter)
	//	{
	//	case 0 :
	//		//shoulderSetAngle(testAngle1, 5);
	//		//shoulderSetPosition(&testPos, 1);
	//		shoulderSetAngle(&testAng, 1);
	//		counter++;
	//	  break;
	//	//case 1:
	//	//	shoulderSetAngle(testAngle2, 5);
	//	//	counter++;
	//	//  break;
	//	}
	//	shoulderRun();
	//}

	//肘关节
	UpdateInputs();
	if (timer > 2)
	{
		Ax = -26.5;
		Ay = 589.763;
		Aphi = 180;
		Ajoint[6] = { 0 };

		kinematics_inverse(Ax, Ay, Aphi, Ajoint);

		double SetShoulderAngle = Ajoint[0];
		shoulderSetAngle(&SetShoulderAngle, 1);

		double SetElbowAngle = Ajoint[1];
		SetRad = SetElbowAngle / 180.0 * Pi;

		elbow.SetTargetRad(SetRad);

		shoulderRun();
		elbow.run();

		UpdateOutputs();
	}

	return hr;
}


void CGivePosition::UpdateInputs()
{
	//elbow.GetAngle(m_Inputs.Angle - 270);//不受力状态时，角度为270，减去，角度会增大//旧的肘

	elbow.GetAngle(350 - m_Inputs.Angle);//不受力状态时，角度为350，减去，角度会减少//新的肘
	timer = m_Inputs.PlcTimer;

}

void CGivePosition::UpdateOutputs()
{
	//电压转换为（0-10V）->（0-32767）
	m_Outputs.m1Int = static_cast<int>(elbow.ShowM1() / 10 * 32767);
	m_Outputs.m2Int = static_cast<int>(elbow.ShowM2() / 10 * 32767);

	m_Outputs.rad = elbow.ShowRad();
	m_Outputs.tarrad = SetRad;
	m_Outputs.m1v = elbow.ShowM1();
	m_Outputs.m2v = elbow.ShowM2();
}

void CGivePosition::shoulderSetPosition(double tarPosition[], int num)
{
	for (int i = 0; i < num; i++)
	{
		if (tarPosition[i] - MyCppPosition[PositionArraySize] > shoulderMaxPos)//判断添加的位置是否距离太远，超过单次移动最大距离，超过则拆分位置
		{
			int pieces = static_cast<int> ((tarPosition[i] - MyCppPosition[PositionArraySize]) / shoulderMaxPos);
			for (int j = 0; j < pieces; j++)
			{
				MyCppPosition[PositionArraySize] = MyCppPosition[PositionArraySize - 1] + tarPosition[i] * 1 / pieces;
				if (PositionArraySize < 99)
				{
					PositionArraySize++;
				}
			}
		}
		else
		{
			MyCppPosition[PositionArraySize] = tarPosition[i];
			if (PositionArraySize < 99)
			{
				PositionArraySize++;
			}
		}
	}
	//TODO:判断两个点之间距离超过限定值，就拆开
	//TODO:如果给定超过数组大小，怎么解决
}

void CGivePosition::shoulderSetAngle(double tarAngle[], int num)
{
	for (int i = 0; i < num; i++)
	{
		double tmpTarPos = tarAngle[i] / 90.0 * 23;//测试，电机位置转动90度时，移动位置为23
		if (tmpTarPos - MyCppPosition[PositionArraySize] > shoulderMaxPos)//判断添加的位置是否距离太远，超过单次移动最大距离，超过则拆分位置
		{
			int pieces = static_cast<int> ((tmpTarPos - MyCppPosition[PositionArraySize]) / shoulderMaxPos);
			for (int j = 0; j < pieces; j++)
			{
				MyCppPosition[PositionArraySize] = MyCppPosition[PositionArraySize - 1] + tmpTarPos * 1 / pieces;
				if (PositionArraySize < 99)
				{
					PositionArraySize++;
				}
			}
		}
		else
		{
			MyCppPosition[PositionArraySize] = tmpTarPos;
			if (PositionArraySize < 99)
			{
				PositionArraySize++;
			}
		}
	}
	//TODO:判断两个点之间距离超过限定值，就拆开
	//TODO:如果给定超过数组大小，怎么解决
}

void CGivePosition::shoulderRun()
{
	if (PositionCount < PositionArraySize)	//没有走完已有坐标，则继续移动
	{

		if (m_Inputs.CanGivenPosition)		//可以给定坐标
		{
			m_Outputs.GivenPosition = MyCppPosition[PositionCount];	//将坐标传给plc
			m_Outputs.IsGivenPositon = TRUE;						//c++给定了坐标
		}
	}


	if ((m_Outputs.IsGivenPositon) && (MyCppPosition[PositionCount] == m_Inputs.NextPosition))
		//当NextPosition已经记录了给定坐标时，认为可以继续给定，将IsGivenPositon设为假
	{
		m_Outputs.IsGivenPositon = FALSE;	//上一次给定坐标已被PLC记录，认为c++未给定下一个坐标，可以继续给定
		++PositionCount;					//将c++坐标移动到下一个
	}
}

///////////////////////////////////////////////////////////////////////////////
HRESULT CGivePosition::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CGivePosition::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}